apiVersion: v1
kind: Service
metadata:
  name: getting-started
spec:
  type: NodePort
  selector:
    app: getting-started
  ports:
    - port: 5000         # Port that the service will expose
      targetPort: 5000   # Port on the container
      nodePort: 30010    # NodePort (optional, Kubernetes will assign one if not specified)
