name: CI with Docker

on:
 workflow_dispatch

env:
 DOCKER_USERNAME: ${{vars.DOCKER_NAME}}
 DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
 DOCKER_IMAGE: santoshguggilla7/getting-started
jobs:
 build-using-docker:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code 
     uses: actions/checkout@v4.2.2

   - name: Setup Kubectl
     uses: azure/setup-kubectl@v4
     with:
       version: latest
   - name: Setup Minikube
     run: |
      minikube start
      kubectl config use-context minikube
   - name: Deployment k8s
     run: |
      kubectl apply -f k8s/deployment.yml
      kubectl apply -f k8s/service.yml
      
